### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by zoyaazhar** [lihas/NeuroPy#11]
I am getting the following error after running the script
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/NeuroPy/NeuroPy/NeuroPy.py", line 146, in __packetParser
    p1 = self.__srl.read(1).encode("hex")  # read first 2 packets

**Comment by rockangator** [comment]
Where you able to solve it?
