### ISSUE TITLE
Unable to get data from mindwave

### ISSUE THREAD

**Issue by Sweetzaline** [lihas/NeuroPy#17]

**Comment by Sweetzaline** [comment]
I am running this program :

from NeuroPy import NeuroPy
from time import sleep

```
> abc = NeuroPy("COM13",9600)
> 
> def attention_callback(attention_value):
>     """this function will be called everytime NeuroPy has a new value for attention"""
>     print ("Value of attention is: ", attention_value)
>     return None
> 
> abc.setCallBack("attention", attention_callback)
> abc.start()
> 
> try:
>     while True:
>         sleep(0.2)
> finally:
>     abc.stop()
```

I am getting the following output:

> 
> > attention:   0%|          | 0/100 [00:00<?, ?it/s]
> meditation:   0%|          | 0/100 [00:00<?, ?it/s]Exception in thread Thread-8:
> Traceback (most recent call last):
>   File "C:\anaconda\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\anaconda\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\sweetie\NeuroPy\NeuroPy.py", line 146, in __packetParser
>     p1 = self.__srl.read(1).encode("hex")  # read first 2 packets
> AttributeError: 'bytes' object has no attribute 'encode'

Please help

**Comment by PetreBoboc** [comment]
Which version of Python are you using?

**Comment by saishan27** [comment]
- Hello, I'm exactly same issues. I'm using following version in Anaconda Prompt

- Python 3.6.0
- - |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32 

- I'm using Brainsense EEG headset which is also using the same TGAM1 which is same to NeuroSky circuit

**Comment by Sweetzaline** [comment]
What was the problem. I completed my project and also forgotten.

**Comment by PetreBoboc** [comment]
Hello, @saishan27!

Can you test this library in Python 2.7? As far as I know, this library does not work with Python 3.x.

**Comment by saishan27** [comment]
![image](https://user-images.githubusercontent.com/22054711/63344324-ca09c400-c36d-11e9-880e-82f59bc4d50f.png)

**Comment by saishan27** [comment]
Hello, @PetreBoboc 
will try and let you know the result

**Comment by saishan27** [comment]
> What was the problem. I completed my project and also forgotten.
> […](#)

Hello @Sweetzaline
- Im unable to get any valid values. All i get for all the function is 0 . and sometimes i get following error similar to yours
"File "C:\Users\sweetie\NeuroPy\NeuroPy.py", line 146, in __packetParser
p1 = self.__srl.read(1).encode("hex") # read first 2 packets
AttributeError: 'bytes' object has no attribute 'encode'"

**Comment by Sweetzaline** [comment]
Yes, YOU CANT GET IT IN PYTHON 3. THAT WAS WHAT I WAS FIGHTING WITH FOR A
LONG TIME.

**Comment by saishan27** [comment]
@Sweetzaline ... Awesome Sauce!. ill try with python 2.7 then... thanks alot

**Comment by Sweetzaline** [comment]
Earlier I was using Python 3. Then I discontinued and used Python 2 that
solved my problem.

**Comment by Sweetzaline** [comment]
Use Python 2.7. If you are doing in Python 3, Make an environment where you
can use both Python 2 and Python 3. Yes this is possible and very feasible.
I did that.

**Comment by Sweetzaline** [comment]
Use Python 2.7. If you are doing in Python 3, Make an environment where you
can use both Python 2 and Python 3. Yes this is possible and very feasible.
I did that. In Anaconda!

**Comment by saishan27** [comment]
I created a new Environment in Anaconda for this project. 
It works fine now i guess
![image](https://user-images.githubusercontent.com/22054711/63346127-fa536180-c371-11e9-8e23-0fed2f664c31.png)

Thanks Alott

**Comment by Sweetzaline** [comment]
Yoohoo! You are done with this problem. Goodluck!!

**Comment by Sweetzaline** [comment]
You welcome!

**Comment by so02s** [comment]
Or you can change lib code for Python3 methods
I suffered for several hours to get everything up and running and connect the headset, it works
