### ISSUE TITLE
I get this error after 10 seconds max

### ISSUE THREAD

**Issue by YannisDC** [lihas/NeuroPy#6]
Unhandled exception in thread started by <bound method NeuroPy.__packetParser of <NeuroPy.NeuroPy.NeuroPy object at 0x1022b7a10>>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/NeuroPy/NeuroPy.py", line 84, in __packetParser
    p2=srl.read(1).encode("hex")
  File "/Library/Python/2.7/site-packages/serial/serialposix.py", line 481, in read
    raise SerialException('read failed: %s' % (e,))
serial.serialutil.SerialException: read failed: (9, 'Bad file descriptor')

**Comment by lihas** [comment]
Is the headset getting disconnected?
